# Generated by Django 5.0.6 on 2024-05-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='pictures/')),
                ('prediction', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Temporary Images',
            },
        ),
    ]
